version: '3.7'

services:

  akaunting:
    container_name: akaunting
    build:
      dockerfile: fpm-alpine-nginx-composer.Dockerfile
      context: .
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-cli.ini:/usr/local/etc/php/php-cli.ini
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  proxy:
    container_name: proxy
    entrypoint: /usr/sbin/nginx
    command: -g "daemon off;"
    build:
      dockerfile: fpm-alpine-nginx-composer.Dockerfile
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    restart: unless-stopped
    env_file:
      - env/db.env

